/* eslint-disable react/jsx-no-undef */
import "@/styles/globals.css";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Provider } from "react-redux";
import store from "@/store/store";
import { useEffect } from "react";
import { useState } from "react";
import { useRouter } from "next/router";


function MyApp({ Component, pageProps }) {


// FROM KW START
  const [user, setUser] =useState({value: null})
  const [key, setKey] = useState()
  const [progress, setProgress] = useState(0)
  const router = useRouter()



  useEffect(() => {
    // router.events.on('routeChangeStart', ()=>{
    //   setProgress(40)
    // })
    // router.events.on('routeChangeComplete', ()=>{
    //   setProgress(400)
    // })
 console.log("hey I am a useEffect from react")
const token = localStorage.getItem('token')
if(token){
  setUser({value: token})
  setKey(Math.random())
}

  }, [router.query])

  const logout =()=>{
    localStorage.removeItem("token")
    setUser({value: null})
    setKey(Math.random())
    router.push('/')
  }
// FROM KW STOP


  return (
    <>
      <Head>
        <title>KoshaliWear || Online Saree Shop</title>
        <meta name="description" content="Generated by creat next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Provider store={store}>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </Provider>
    </>
  );

  {key && <Header logout={logout} user={user} key={key} />}

}
export default MyApp
